export const TODO_LIST_SUCCESS = 'TODO_LIST_SUCCESS'
export const TODO_LIST_ERROR = 'TODO_LIST_ERROR'

export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR'

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_ERROR = 'DELETE_TODO_ERROR'

export const DONE_TODO_SUCCESS = 'DONE_TODO_SUCCESS'
export const DONE_TODO_ERROR = 'DONE_TODO_ERROR'

export const PENDING_TODO_SUCCESS = 'PENDING_TODO_SUCCESS'
export const PENDING_TODO_ERROR = 'PENDING_TODO_ERROR'
